name: PHP Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Create the data/email directory
      run: |
        mkdir ./data ./data/emails

    - name: Install dependencies with latest
      run: composer install --prefer-dist

    - name: Run test suite
      run: composer run-script test

    - name: Update dependencies with --prefer-lowest
      run: composer update --prefer-lowest

    - name: Run test suite
      run: composer run-script test
